name: Python application

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set env
      run: |
        python3 -m venv env
        ln -s env/bin/activate
        . activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt 
    - name: Test with pytest
      run: |
        py.test tests
